#!/usr/bin/env python

import roslib
import rospy

from movement import Movement
from bumperaction import BumperAction
from laseraction import LaserAction


RIGHT = "RIGHT"
LEFT = "LEFT"

def main():

    rospy.init_node('robotNavigation', anonymous=True)

    bumper_sensor = BumperAction()
    movement = Movement()
    laser_sensor = LaserAction()

    while not rospy.is_shutdown():

        if bumper_sensor.get_bumper_collision():
            movement.halt_movement()

        else:

            if laser_sensor.right_laser < 1 and laser_sensor.center_laser < 1 and laser_sensor.left_laser < 1:
                movement.turn_around()
            elif (laser_sensor.left_laser + laser_sensor.right_laser + laser_sensor.center_laser) == 3:
                movement.forward_and_turn()
            elif laser_sensor.nearest_section == laser_sensor.left_laser:
                #debug
                print("Entering LEFT!")
                movement.turn_to_sides(RIGHT)
            elif laser_sensor.nearest_section == laser_sensor.right_laser:
                #debug
                print("Entering RIGHT!")
                movement.turn_to_sides(LEFT)


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
